### ISSUE TITLE
Optional text for regexp check (feature wish)

### ISSUE THREAD

**Issue by elaratain** [splitbrain/dokuwiki-plugin-bureaucracy#143]
Would be nice to be able to "change the checked against" text. I think most users do not understand long regular expressions like `[A-Z]{2}(\s?)(\d{2,4}\s?)(\d{4}\s?){4}(\d{2,4}\s?)?` and would be happier with e.g. `AA00 0000 0000 0000 00`

**Comment by Klap-in** [comment]
Feature is implemented. You can use now `"**Your message"` or `**Message` to replace the default 'checked against..' text.

**Comment by asheenlevrai** [comment]
I'm sorry, could you please explain how this new feature works? I mean how to use it properly.
Tx
-a-

**Comment by Klap-in** [comment]
Good question, I added the syntax also to the wiki page of the plugin.

```
textbox "Your pagename" /^[^\/:]+$/ "**Don't use / or : in your page name"
```

**Comment by asheenlevrai** [comment]
Thanks,

For some reason DW doesn't see that the plugin should be updated. The documentation page still refers to 2015-09-14 as the last update while your change is mentioned in the "changes" section.

Best,
-a-

**Comment by Klap-in** [comment]
Aha, you're right, thanks again!
I updated the update date, so update mechanism should pick it up again.

**Comment by asheenlevrai** [comment]
Cool :) Tx!

Now I noticed the "new" error message is now displayed inside the page (inside the square, below the name of the page) rather than above the page (outside the square, above the name of the page) like other error messages.

In our situation, errors messages are not seen by users when submitting data with errors since the form is located at the bottom of a long page and error messages do not cause scroll up back to top...

Now, since the "new" error message is displayed in a different place (compared to default error messages), would there be any way to have it rather displayed just next to the form? Like just above it or below it?. This way users could easily notice whenever they have made any mistake.

Tx
-a-
