### ISSUE TITLE
PHP error after upgrading to 2021-03-19

### ISSUE THREAD

**Issue by WordsOfMe** [splitbrain/dokuwiki-plugin-bureaucracy#294]
Upgrading to the latest version brings dokuwiki down:

`[Mon Jun 21 23:36:45.065641 2021] [fcgid:warn] [pid 19833] [client 192.0.2.0:50762] mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected '?' in /var/www/wiki.example.com/lib/plugins/bureaucracy/syntax.php on line 542, referer: https://wiki.example.com/`

_(redacted for privacy)_

**Comment by Klap-in** [comment]
On line 542 we find:
https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/blob/3373d1524a23dce933a0a9b62b267eafebd4c49c/syntax.php#L542

I guess this is recent php syntax, probably you are using an older php version.

Which version of php do you use on your system?

**Comment by WordsOfMe** [comment]
php 5.6, which satisfies the dokuwiki requirements as per [https://www.dokuwiki.org/requirements](https://www.dokuwiki.org/requirements)

**Comment by Klap-in** [comment]
Sure. 
It is introduced by https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/commit/dbe43fdf031ae1f42760b50ed07505202178db79

This is syntax since php7. https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

(Note please note that the next DokuWiki will drop support for all versions before 7.2, so if the fix here is not coming quick enough you can change this line yourself, or already update to newer version of php)

e.g. 
```
 $match[2] = $match[2] ? $match[2] : $conf['dformat']; 
```

**Comment by WordsOfMe** [comment]
...understood. So as bureaucracy now requires php 7.x and the next dokuwiki release will require php 7.2 anyway I will upgrade the php packages right now. Thanks!
